
/* CREATING TABLE IN DATABASE */

CREATE TABLE TABLE_NAME (
    id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);